name: First assessment

on: push

jobs:
  lint:
    runs-on: ubuntu_latest
    steps:
      - name: Linting
        run: echo "lint"

  test:
    needs: lint
    runs-on: ubuntu_latest
    steps: 
      - name: Testing
        run: echo "test"

  build:
    needs: test
    runs-on: ubuntu_latest
    steps:
      - name: Build
        run: echo "build"

